### ISSUE TITLE
Bugs in concat and slice

### ISSUE THREAD

**Issue by wshager** [wishfoundry/rrbit#6]
I think here's a bug in append at https://github.com/wishfoundry/rrbit/blob/master/src/append.js#L96
Shouldn't a0 and b0 be the other way around?

Furthermore, there's a bug in https://github.com/wishfoundry/rrbit/blob/master/src/internal.js#L34
I think when the height is not the same as the original, it should be elevated.

FYI I'm working on a slightly different approach (using a wrapping prototype, with a tail and a more lightweight root, without the verbose accessors) and borrowed much of your good work, hence these suggestions. My apologies in advance for not adhering to the open source code of conduct, but perhaps we can merge this stuff at some stage.

**Comment by wishfoundry** [comment]
Hi @wshager, Thanks for the comment.

There are a couple issues in the current version like the ones mentioned, and some with set/unsafeSet as well.

I'm working on a rewrite ATM that will support some of the more recent advances in RRB research including "transience"(optimistic push instead of a full slice), start/end index offset for efficient take/drop, and a "focus" (like clojure's tail optimization, but for either end). I think these advances are significant enough to cease continued work on the current branch.

I'm open to merging contributions, so long as they fit the goals of this project. Which currently is to write this in maximally flexible set of operations that can be applied to any object, rather than as class members. The goal is to allow users build their own vector class types and error handling scheme as fits their language/environment, but maintain the core logic and optimizations here. Possibly in future, having a sister project with a reference vector class implementation.

**Comment by wshager** [comment]
All right, I'll close this then. For me anything that will outperform Immutable.js and works for my use case is sufficient, so I'll stick to the code that works so far. What was the problem with set? It seems to work fine...

**Comment by wishfoundry** [comment]
set only clones the leaf node currently, it needs to also clone the adjusted tree hierarchy or you mutate previous snapshots. It's the kind of bug won't show up when testing a single list, as the final list is correct.

if your trying to outperform immutablejs then know that  splitting, concat and converting from a native array is very fast but looping over and appending/prepending/updating are not so much... I'd highly recommend looking into optimized ways to generate your vector by either writing a small builder util or look into transforms lib like transducers along with some of the code in fromArray().

**Comment by wshager** [comment]
Thanks! That seems easy to fix as it's a straightforward path copy. 

From my benchmarks it's clear that native concat is at minimum 10 times faster no matter what.  I don't really understand yet though. In practice lazy slice will be acceptable, but lazy slice+concat seems somewhat mind bending... Like I said, I'll stick to this and run some thorough tests.

**Comment by wishfoundry** [comment]
I wouldn't pursue lazy slice, but rather a start offset and a end/length limit should give you the better perf benefits and a simpler mental overhead. The only time you need to perform the actual work of slicing is during concat. And you should be able to outperform native concat, at least on large collections.

the simplest explanation I've found on rrb concat is probably [Phil Bagwell's video](https://www.youtube.com/watch?v=K2NYwP90bNs)

**Comment by wshager** [comment]
Yep, watched it so many times I can imitate the accent... where was he from anyway? Still curious what he would've come up with next.

**Comment by wshager** [comment]
Unfortunately there appear to be more errors for higher trees. I believe the source you used came from Xashili, and concat there elevates trees to the same height before concatenation. Did you choose another solution intentionally?

**Comment by wishfoundry** [comment]
This project was originally an experiment aiming to learn Elm and solve a of [Elm's core Array](https://github.com/elm-lang/core/blob/master/src/Native/Array.js) bugs, wrap a few test cases around them, and then try improving performance.  I abandoned that effort as, like you have noticed, it just keeps on giving the further you dig :)

I believe xashili donated the current Elm Array from his own github repo, which he sourced from a gist

**Comment by wshager** [comment]
My test was somewhat like the one described by Bagwell in the video: slice + concat consecutively until you'll get a very unbalanced tree. At some height it'll start throwing errors. Should I create an issue for this?

**Comment by wishfoundry** [comment]
I'm not opposed to a PR if you want

**Comment by wshager** [comment]
See #7.

There's still one issue where every other consecutive "slice into 2 with random cut and re-concatenate" runs I encounter a wrong value on and around the insertion index. This can be perceived easily in a range of 0-N integers, as the index should be equal to the value. Remarkable is that the value is off by 2*M consistently. I fear a typo somewhere...

**Comment by wshager** [comment]
Strange, it's just an index miss, if I create a JS array from the tree the value matches the index.

**Comment by wishfoundry** [comment]
Do you mind including your tests? 
Even if their currently failing, it's better to know

**Comment by wshager** [comment]
The size tables are incorrectly updated in shuffle. The setEither/getEither is hard to understand for me, but sometimes a size is read from the wrong table. Could that part be simplified? I guess you should be able to read the correct size from the table.

**Comment by wshager** [comment]
I mean the length from the child array could be used instead.

**Comment by wshager** [comment]
The size you want to find is often not on the b size table.

**Comment by wshager** [comment]
And sometimes it's not in the a size table either... This seems to work:

`
var newA = allocate(a.height, Math.min(_const.M, a.length + b.length - toRemove));
	var newB = allocate(a.height, Math.max(0,newA.length - (a.length + b.length - toRemove)));
	// Skip the slots with size M. More precise: copy the slot references
	// to the new node
	var read = 0;
	let aLen = a.length;
	let either, fromA;
	let newALen = newA.length;
	while ((fromA = read < aLen, either = getEither(a, b, read),either.length % _const.M === 0)) {
		let fromNewA = read < newALen;
		if(fromNewA) newA[read] = either;
		else newB[read - newALen] = either;
		let size = fromNewA ? a.sizes[read] : b.sizes[read - newALen];
		if(!size) size = newA.sizes[read - 1] + either.length;
		if(fromNewA) newA.sizes[read] = size;
		else newB.sizes[read - newALen] = size;
		read++;
	}
`

**Comment by wshager** [comment]
Nope, there's still one edge case... my guess is I'm reading from the wrong size table when size is undefined. It rarely occurs though.

**Comment by wshager** [comment]
Ah sorry that was my version of the code. Anyway, if you just add length(either) to the previous read from a's table sizes you'll get the correct last size.
